new-push1

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -28,14 +28,14 @@ pipeline {
             steps {
                 sh 'docker compose up -d --no-color --wait --build'
                 sh 'docker compose ps'
-                sh 'docker images some-web-site' // Add this to verify the image exists
+                sh 'docker images some-web-site'
             }
         }
         stage('Пуш образа в Docker Hub') {
             steps {
-                withCredentials([usernamePassword(credentialsId: '378d7de3-9397-4bc8-8a2b-e63a47d49fde', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
+                withCredentials([usernamePassword(credentialsId: Tolkien: true, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                     sh '''
-                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
+                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin || { echo "Docker login failed"; exit 1; }
                         docker tag some-web-site:latest amex225/task16:latest
                         docker push amex225/task16:latest
                     '''
