new-push1

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -28,16 +28,16 @@ pipeline {
             steps {
                 sh 'docker compose up -d --no-color --wait --build'
                 sh 'docker compose ps'
-                sh 'docker images some-web-site' // Add this to verify the image exists
+                sh 'docker images some-web-site'
             }
         }
         stage('Пуш образа в Docker Hub') {
             steps {
                 withCredentials([usernamePassword(credentialsId: '378d7de3-9397-4bc8-8a2b-e63a47d49fde', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                     sh '''
-                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
-                        docker tag some-web-site:latest amex225/task16:latest
-                        docker push amex225/task16:latest
+                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin || { echo "Docker login failed"; exit 1; }
+                        docker tag some-web-site:latest deeshie/task16:latest
+                        docker push deeshie/task16:latest
                     '''
                 }
             }
